"""app.analysis — LLM-backed chain analysis package."""

from app.analysis.adapters import (
    AnalysisAdapter,
    AnalysisInput,
    AnalysisResponse,
    ChainAnalysisResult,
    ChainRankingEntry,
    ChatMessage,
    EmptyRenderedMessagesError,
    GitHubModelsAdapter,
    GitHubModelsAPIError,
    GitHubModelsConfig,
    GitHubModelsError,
    MissingTokenError,
    ModelProviderInfo,
    PromptProfile,
    PromptRenderer,
    PromptTaskType,
    RankingOutput,
)
from app.analysis.engine import (
    AnalysisEngine,
    AnalysisEngineConfig,
    DryRunAnalysisAdapter,
)
from app.analysis.prompts import (
    FileSystemPromptRenderer,
    MissingPromptProfileError,
    MissingPromptTemplateError,
    PromptProfileConfig,
    PromptProfileError,
    PromptProfileLoader,
    PromptTemplateError,
    TaskTemplateMapping,
)
from app.analysis.react import (
    GrouperContext,
    ReActAnalysisEngine,
    ReActContext,
    ReActEngineConfig,
    ReActSession,
    ReActStep,
    Tool,
    ToolRegistry,
    akshare_query_tool,
    build_grouper_prompt_context,
    build_react_finalize_prompt_context,
    build_react_step_prompt_context,
    tool_registry,
    web_fetch_tool,
    web_search_tool,
)

__all__ = [
    # contracts
    "AnalysisAdapter",
    "AnalysisInput",
    "AnalysisResponse",
    "ChainAnalysisResult",
    "ChainRankingEntry",
    "ModelProviderInfo",
    "PromptProfile",
    "PromptTaskType",
    "RankingOutput",
    # github_models
    "ChatMessage",
    "EmptyRenderedMessagesError",
    "GitHubModelsAdapter",
    "GitHubModelsAPIError",
    "GitHubModelsConfig",
    "GitHubModelsError",
    "MissingTokenError",
    "PromptRenderer",
    # engine
    "AnalysisEngine",
    "AnalysisEngineConfig",
    "DryRunAnalysisAdapter",
    # prompts
    "FileSystemPromptRenderer",
    "MissingPromptTemplateError",
    "PromptTemplateError",
    # profile management
    "TaskTemplateMapping",
    "PromptProfileConfig",
    "PromptProfileLoader",
    "PromptProfileError",
    "MissingPromptProfileError",
    # react
    "Tool",
    "ToolRegistry",
    "tool_registry",
    "web_search_tool",
    "web_fetch_tool",
    "akshare_query_tool",
    "ReActStep",
    "ReActSession",
    "GrouperContext",
    "ReActContext",
    "build_grouper_prompt_context",
    "build_react_step_prompt_context",
    "build_react_finalize_prompt_context",
    "ReActAnalysisEngine",
    "ReActEngineConfig",
]
